In [1]:
import pandas as pd
import pip
pip.main(["install", "openpyxl"])

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

Requirement already satisfied: openpyxl in c:\users\thanos\desktop\απθ\απθ\διπλωματικη\cfd_venv\test_venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\thanos\desktop\απθ\απθ\διπλωματικη\cfd_venv\test_venv\lib\site-packages (from openpyxl) (2.0.0)

WARNING: You are using pip version 20.2.3; however, version 25.2 is available.
You should consider upgrading via the 'C:\Users\thanos\Desktop\ΑΠΘ\ΑΠΘ\διπλωματικη\cfd_venv\test_venv\Scripts\python.exe -m pip install --upgrade pip' command.

0

In [2]:
df = pd.read_excel("data_test.xlsx")
df.head()

,Απόφαση δικαστηρίου,Έτος,Περίληψη,link
0,ΜΠρΚορίνθου 132/2025,2025,Δεκτή αγωγή (Τακτική Διαδικασία) εξάλειψης υπο...,https://www.dsanet.gr/Epikairothta/Nomologia/n...
1,ΜΠρΑθ 71530/2025,2025,Τακτική διαδικασία - Αγωγή αποζημίωσης χρήσης ...,https://www.dsanet.gr/Epikairothta/Nomologia/Μ...
2,ΜΠρΑθ 3878/2025,2025,Αίτηση αναστολής κατά διαταγής πληρωμής και επ...,https://www.dsanet.gr/Epikairothta/Nomologia/Μ...
3,ΜΠρΑθ 2833/2025,2025,Αίτηση αναστολής κατά διαταγής πληρωμής και επ...,https://www.dsanet.gr/Epikairothta/Nomologia/Μ...
4,ΜΠρΑθ 2066/2025,2025,Ανακοπή 632 και 933 ΚΠολΔ κατά διαταγής πληρωμ...,https://www.dsanet.gr/Epikairothta/Nomologia/Μ...

In [3]:
import re

def extract_court_type(court_name):
    """
    Extracts the type of court (e.g., 'Εφ' for Εφετείο) from the abbreviated name.

    Args:
        court_name (str): The abbreviated court name (e.g., 'ΜονΕφΠειρ').

    Returns:
        str or None: The extracted court type abbreviation, or None if not found.
    """

    cleaned_name = re.sub(r'\s*\(.*?\)\s*', '', court_name)

    # Common Greek court type abbreviations and their full names
    court_types = {
        'Εφ': 'Εφετείο',
        'ΜΟΕ': 'Μικτό Ορκωτό Εφετείο',
        'ΣυμβΕφ': 'Συμβούλιο Εφετών',
        'Πρ': 'Πρωτοδικείο',
        'Ειρ': 'Ειρηνοδικείο',
        'ΣτΕ': 'Συμβούλιο της Επικράτειας',
        'ΣΤΕ': 'Συμβούλιο της Επικράτειας',
        'ΑναθΔικ': 'Αναθεωρητικό Δικαστήριο',
        'ΑΠ': 'Άρειος Πάγος',
        'ΑΠΔ': 'Αρχή Προστασίας Δεδομένων',
        'ΕλΣ': 'Ελεγκτικό Συνέδριο',
        'ΑΕΔ': 'Ανώτατο Ειδικό Δικαστήριο',
        'Διαιτ': 'Διαιτητικό Δικαστήριο',
        'Διατ': 'Διάταξη',
        'ΟΠΕΚΑ': 'Οργανισμός Προνοιακών Επιδομάτων και Κοινωνικής Αλληλεγγύης',
        'Ναυτ': 'Ναυτικό'
    }

    # Sort keys by length descending to match longer, more specific terms first
    sorted_keys = sorted(court_types.keys(), key=len, reverse=True)

    for key in sorted_keys:
        if key in cleaned_name:
            return court_types[key]

    return '-' # Return '-' if no known type is found

In [4]:
df["Τύπος δικαστηρίου"] = df["Απόφαση δικαστηρίου"].apply(extract_court_type)
df.head()

,Απόφαση δικαστηρίου,Έτος,Περίληψη,link,Τύπος δικαστηρίου
0,ΜΠρΚορίνθου 132/2025,2025,Δεκτή αγωγή (Τακτική Διαδικασία) εξάλειψης υπο...,https://www.dsanet.gr/Epikairothta/Nomologia/n...,Πρωτοδικείο
1,ΜΠρΑθ 71530/2025,2025,Τακτική διαδικασία - Αγωγή αποζημίωσης χρήσης ...,https://www.dsanet.gr/Epikairothta/Nomologia/Μ...,Πρωτοδικείο
2,ΜΠρΑθ 3878/2025,2025,Αίτηση αναστολής κατά διαταγής πληρωμής και επ...,https://www.dsanet.gr/Epikairothta/Nomologia/Μ...,Πρωτοδικείο
3,ΜΠρΑθ 2833/2025,2025,Αίτηση αναστολής κατά διαταγής πληρωμής και επ...,https://www.dsanet.gr/Epikairothta/Nomologia/Μ...,Πρωτοδικείο
4,ΜΠρΑθ 2066/2025,2025,Ανακοπή 632 και 933 ΚΠολΔ κατά διαταγής πληρωμ...,https://www.dsanet.gr/Epikairothta/Nomologia/Μ...,Πρωτοδικείο

In [5]:
df["Τύπος δικαστηρίου"].value_counts()

Τύπος δικαστηρίου
Άρειος Πάγος                                                   20776
Πρωτοδικείο                                                      613
Εφετείο                                                          324
Ειρηνοδικείο                                                     176
Συμβούλιο της Επικράτειας                                         65
-                                                                 11
Συμβούλιο Εφετών                                                  11
Διάταξη                                                            4
Αρχή Προστασίας Δεδομένων                                          4
Μικτό Ορκωτό Εφετείο                                               4
Διαιτητικό Δικαστήριο                                              3
Ανώτατο Ειδικό Δικαστήριο                                          3
Ελεγκτικό Συνέδριο                                                 2
Αναθεωρητικό Δικαστήριο                                            1
Ναυτικό                                                            1
Οργανισμός Προνοιακών Επιδομάτων και Κοινωνικής Αλληλεγγύης        1
Name: count, dtype: int64

In [9]:
no_name_values = df['Τύπος δικαστηρίου'] == '-'
result = df.loc[no_name_values, 'Απόφαση δικαστηρίου']
print(result)

12       Διαπιστωτική πράξη του Εισηγητή Πτωχεύσεων Μικ...
61              Διάταξη του Εισηγητή Πτωχεύσεων 21485/2025
111                      Ελ.Σ. (Συμβ. Τμήμα VI)  1434/2024
493                               ΤρΠλημΚορίνθου 1597/2022
594                                  ΣυμβΠλημΘεσ 1586/2022
628                                   ΣυμβΠλημΘεσ 707/2022
728      Ειδικό Δικαστήριο άρθρου 88 παρ. 2 Σ (Μισθοδικ...
1036                                        ΜΠΑθ 1276/2020
1052                                          ΜΠΑθ 70/2020
1334                                          ΜΠΛαρ 3/2019
21997                  ΕΔΑΔ ΝΙΚΑ κατά ΕΛΛΑΔΟΣ (18.03.2021)
Name: Απόφαση δικαστηρίου, dtype: object

In [11]:
df.to_excel("law_cases.xlsx", index=False)